---
- hosts: localhost
  tasks:
  - name: create key pair using provided key_material
    ec2_key:
      name: bastion_host 
      region: us-east-1
      #state: present
      # some changes
      key_material: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2QU7eyspnY4Erq65/mgIMv5M5Rf7IF0hMel6r3aI9JxUhhRiD/xC4FDmlRaxfYx/AtqsZLMzTw+K1dyzMAIM1K33Vhg2wUy3q/nE34Onrl2Z+KXSgRpHi5TvxKWJmEOBm/lCPFpfB4LCTAS63/nGTHXtM7PiuHpcm+ATis1mLqfYxHz9hAfONpsNTNpiy4r+s3ggWSH2e/0DpnZ52EiedNgXU7PscHqKQVDMO2TMwzoFsqxs8spApInoNMYzRPTnScucxOIiLYwwwB1tKJCDd16IvoWcOd0o0QE+FUY2lhLMVlCILoqmooTHn05ia9BfRWIdbqsDiEcCmwyEW0c2N ec2-user@ip-172-31-29-150.eu-west-2.compute.internal'